# Generated by Django 5.2.14 on 2026-06-04 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocal_type', models.CharField(choices=[('not_sure', 'Not Sure'), ('bass', 'Bass'), ('tenor', 'Tenor'), ('alto', 'Alto'), ('soprano', 'Soprano')], default='not_sure', max_length=20)),
                ('lowest_note', models.IntegerField(blank=True, null=True)),
                ('highest_note', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
